# Generated by Django 3.1 on 2020-08-25 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievements',
            name='description',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='details',
            name='contactNo',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='details',
            name='description',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='details',
            name='profile',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='education',
            name='course',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='education',
            name='institution',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='experience',
            name='company',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='experience',
            name='profile',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='interests',
            name='interest',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='languagesknown',
            name='language',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='personalskills',
            name='skill',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='projects',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='projects',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='skills',
            name='skill',
            field=models.CharField(default='', max_length=30),
        ),
    ]
