# Generated by Django 3.1 on 2020-08-31 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_auto_20200825_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languagesknown',
            name='readlevel',
            field=models.CharField(choices=[('Advanced', 'Advanced'), ('Intermediate', 'Intermediate'), ('Beginner', 'Beginner')], max_length=12),
        ),
        migrations.AlterField(
            model_name='languagesknown',
            name='writelevel',
            field=models.CharField(choices=[('Advanced', 'Advanced'), ('Intermediate', 'Intermediate'), ('Beginner', 'Beginner')], max_length=12),
        ),
        migrations.AlterField(
            model_name='skills',
            name='level',
            field=models.CharField(choices=[('Advanced', 'Advanced'), ('Intermediate', 'Intermediate'), ('Beginner', 'Beginner')], max_length=12),
        ),
    ]
