# Generated by Django 3.1 on 2020-09-05 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_auto_20200831_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='profilePic',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
