# Generated by Django 3.1 on 2020-09-05 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0004_details_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='profilePic',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
