# Generated by Django 3.1 on 2020-09-16 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0005_auto_20200905_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='profilePicPresent',
            field=models.BooleanField(default=False),
        ),
    ]
