# Generated by Django 3.1 on 2020-09-20 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('work', '0006_details_profilepicpresent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.BooleanField(default=False)),
                ('projects', models.BooleanField(default=False)),
                ('education', models.BooleanField(default=False)),
                ('skills', models.BooleanField(default=False)),
                ('personalskills', models.BooleanField(default=False)),
                ('languagesknown', models.BooleanField(default=False)),
                ('interests', models.BooleanField(default=False)),
                ('achievements', models.BooleanField(default=False)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
