# Generated by Django 3.1 on 2020-09-26 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0007_cards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='gitHub',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='details',
            name='linkedIn',
            field=models.URLField(default=''),
        ),
    ]
