# Generated by Django 3.1 on 2020-09-26 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0008_auto_20200926_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languagesknown',
            name='readlevel',
            field=models.CharField(choices=[('Advanced', 'Advanced'), ('Intermediate', 'Intermediate'), ('Beginner', 'Beginner')], default='Beginner', max_length=12),
        ),
        migrations.AlterField(
            model_name='languagesknown',
            name='writelevel',
            field=models.CharField(choices=[('Advanced', 'Advanced'), ('Intermediate', 'Intermediate'), ('Beginner', 'Beginner')], default='Beginner', max_length=12),
        ),
    ]
