# Generated by Django 3.1 on 2020-09-26 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0009_auto_20200926_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='level',
            field=models.CharField(choices=[('Advanced', 'Advanced'), ('Intermediate', 'Intermediate'), ('Beginner', 'Beginner')], default='Beginner', max_length=12),
        ),
    ]
