# Generated by Django 3.1 on 2020-09-05 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200831_2351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='ispasswordmatch',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='passwordcheck',
        ),
    ]
